### ISSUE TITLE
Dependencies are installed but not found

### ISSUE THREAD

**Issue by nulaft** [SBCV/Blender-Addon-Photogrammetry-Importer#38]
I would like to use this add-on for importing point cloud data with color.
I'm using blender 2.93. I've installed this add-on and tried downloading and installing the optional dependencies using the GUI. It seems to install the dependencies, however the GUI still says that they are not installed, even after restarting blender.

This is what is printed to the command line:
```Read prefs: /home/myname/.config/blender/2.93/config/userpref.blend
INFO:root:INFO: Registered Photogrammetry Import Export Addon with 52 modules
INFO:root:INFO: Installing pip!
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /tmp/tmpgh9pe92n
Requirement already satisfied: setuptools in ./.local/lib/python3.9/site-packages (49.2.1)
Requirement already satisfied: pip in ./.local/lib/python3.9/site-packages (21.2.4)
/home/myname/.config/blender/2.93/scripts/addons/photogrammetry_importer/preferences/dependency.py:122: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  python_exe_fp = bpy.app.binary_path_python
INFO:root:INFO: Installing dependency with ['/snap/blender/460/2.93/python/bin/python3.9', '-m', 'pip', 'install', '--no-cache-dir', 'pillow']
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pillow in ./.local/lib/python3.9/site-packages (8.3.1)
INFO:root:INFO: Installing pip!
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /tmp/tmp8fwcxe8j
Requirement already satisfied: setuptools in ./.local/lib/python3.9/site-packages (49.2.1)
Requirement already satisfied: pip in ./.local/lib/python3.9/site-packages (21.2.4)
INFO:root:INFO: Installing dependency with ['/snap/blender/460/2.93/python/bin/python3.9', '-m', 'pip', 'install', '--no-cache-dir', 'lazrs']
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lazrs in ./.local/lib/python3.9/site-packages (0.2.5)
INFO:root:INFO: Installing pip!
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /tmp/tmps4ghxu04
Requirement already satisfied: setuptools in ./.local/lib/python3.9/site-packages (49.2.1)
Requirement already satisfied: pip in ./.local/lib/python3.9/site-packages (21.2.4)
INFO:root:INFO: Installing dependency with ['/snap/blender/460/2.93/python/bin/python3.9', '-m', 'pip', 'install', '--no-cache-dir', 'pylas']
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pylas in ./.local/lib/python3.9/site-packages (0.4.3)
Requirement already satisfied: numpy in ./.local/lib/python3.9/site-packages (from pylas) (1.21.2)
INFO:root:INFO: Installing pip!
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /tmp/tmpqu_o_dja
Requirement already satisfied: setuptools in ./.local/lib/python3.9/site-packages (49.2.1)
Requirement already satisfied: pip in ./.local/lib/python3.9/site-packages (21.2.4)
INFO:root:INFO: Installing dependency with ['/snap/blender/460/2.93/python/bin/python3.9', '-m', 'pip', 'install', '--no-cache-dir', 'pyntcloud']
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyntcloud in ./.local/lib/python3.9/site-packages (0.1.5)
Requirement already satisfied: pandas in ./.local/lib/python3.9/site-packages (from pyntcloud) (1.3.2)
Requirement already satisfied: scipy in ./.local/lib/python3.9/site-packages (from pyntcloud) (1.7.1)
Requirement already satisfied: numpy in ./.local/lib/python3.9/site-packages (from pyntcloud) (1.21.2)
Requirement already satisfied: pytz>=2017.3 in ./.local/lib/python3.9/site-packages (from pandas->pyntcloud) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in ./.local/lib/python3.9/site-packages (from pandas->pyntcloud) (2.8.2)
Requirement already satisfied: six>=1.5 in ./.local/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas->pyntcloud) (1.16.0)
Info: Installing pip!
Info: Installing dependency with ['/snap/blender/460/2.93/python/bin/python3.9', '-m', 'pip', 'install', '--no-cache-dir', 'pillow']
Info: Installing pip!
Info: Installing dependency with ['/snap/blender/460/2.93/python/bin/python3.9', '-m', 'pip', 'install', '--no-cache-dir', 'lazrs']
Info: Installing pip!
Info: Installing dependency with ['/snap/blender/460/2.93/python/bin/python3.9', '-m', 'pip', 'install', '--no-cache-dir', 'pylas']
Info: Installing pip!
Info: Installing dependency with ['/snap/blender/460/2.93/python/bin/python3.9', '-m', 'pip', 'install', '--no-cache-dir', 'pyntcloud']

```

**Comment by SBCV** [comment]
I think this is caused by the fact that you don't have no rights to write to the location - checkout the following line of your log
> Defaulting to user installation because normal site-packages is not writeable
Can you run Blender with administrator rights? Or use a local Blender installation?

**Comment by nulaft** [comment]
I tried running blender with sudo (on ubuntu), however blender acts as if it was a fresh install with all settings and add-ons wiped. And it won't let me install the add-on because it only allows access to the root directory.

I have the same problem on my windows machine, also running blender 2.93. Running it with admin rights doesn't change anything.

The windows log:
```
INFO:root:INFO: Pip already installed. Using existing pip installation (20.2.3)
C:\Users\myname\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\photogrammetry_importer\preferences\dependency.py:122: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  python_exe_fp = bpy.app.binary_path_python
INFO:root:INFO: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'pillow']
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pillow in c:\users\myname\appdata\roaming\python\python39\site-packages (8.3.1)
WARNING: You are using pip version 20.2.3; however, version 21.2.4 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.EXE -m pip install --upgrade pip' command.
INFO:root:INFO: Pip already installed. Using existing pip installation (20.2.3)
INFO:root:INFO: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'lazrs']
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lazrs in c:\users\myname\appdata\roaming\python\python39\site-packages (0.3.1)
WARNING: You are using pip version 20.2.3; however, version 21.2.4 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.EXE -m pip install --upgrade pip' command.
INFO:root:INFO: Pip already installed. Using existing pip installation (20.2.3)
INFO:root:INFO: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'pylas']
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pylas in c:\users\myname\appdata\roaming\python\python39\site-packages (0.4.3)
Requirement already satisfied: numpy in c:\program files\blender foundation\blender 2.93\2.93\python\lib\site-packages (from pylas) (1.19.5)
WARNING: You are using pip version 20.2.3; however, version 21.2.4 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.EXE -m pip install --upgrade pip' command.
INFO:root:INFO: Pip already installed. Using existing pip installation (20.2.3)
INFO:root:INFO: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'pyntcloud']
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyntcloud in c:\users\myname\appdata\roaming\python\python39\site-packages (0.1.5)
Requirement already satisfied: numpy in c:\program files\blender foundation\blender 2.93\2.93\python\lib\site-packages (from pyntcloud) (1.19.5)
Requirement already satisfied: scipy in c:\users\myname\appdata\roaming\python\python39\site-packages (from pyntcloud) (1.7.1)
Requirement already satisfied: pandas in c:\users\myname\appdata\roaming\python\python39\site-packages (from pyntcloud) (1.3.2)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\myname\appdata\roaming\python\python39\site-packages (from pandas->pyntcloud) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\myname\appdata\roaming\python\python39\site-packages (from pandas->pyntcloud) (2021.1)
Requirement already satisfied: six>=1.5 in c:\users\myname\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.7.3->pandas->pyntcloud) (1.16.0)
WARNING: You are using pip version 20.2.3; however, version 21.2.4 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.EXE -m pip install --upgrade pip' command.
Info: Pip already installed. Using existing pip installation (20.2.3)
Info: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'pillow']
Info: Pip already installed. Using existing pip installation (20.2.3)
Info: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'lazrs']
Info: Pip already installed. Using existing pip installation (20.2.3)
Info: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'pylas']
Info: Pip already installed. Using existing pip installation (20.2.3)
Info: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'pyntcloud']
```

The dependency installation status on both machines is "not installed" for everything.

It seems like
```
Defaulting to user installation because normal site-packages is not writeable
```
might be the problem here, perhaps blender doesn't use user installations?

**Comment by SBCV** [comment]
I think that depends how you have installed Blender. Have you tried to install the packages manually? 
(i.e. running `pip install <package>)`
and then verified that the import works?

**Comment by nulaft** [comment]
I have tried to install the packages manually. I followed these [instructions](https://blender-addon-photogrammetry-importer.readthedocs.io/en/latest/installation.html), and importing pyntcloud works. But they're not detected by the add-on.

Installing pip:
```
PS D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\bin> ."D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\bin\python.exe" get-pip.py
D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
Collecting pip
  Downloading pip-21.2.4-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 6.4 MB/s
Collecting wheel
  Downloading wheel-0.37.0-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, pip
  WARNING: The script wheel.exe is installed in 'D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
  WARNING: The scripts pip.exe, pip3.9.exe and pip3.exe are installed in 'D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-21.2.4 wheel-0.37.0
```

Installing packages:
```
PS D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\Scripts> ."D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\Scripts\pip.exe" install pillow
Requirement already satisfied: pillow in c:\users\myname\appdata\roaming\python\python39\site-packages (8.3.1)
PS D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\Scripts> ."D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\Scripts\pip.exe" install lazrs
Requirement already satisfied: lazrs in c:\users\myname\appdata\roaming\python\python39\site-packages (0.3.1)
PS D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\Scripts> ."D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\Scripts\pip.exe" install laspy
Collecting laspy
  Downloading laspy-2.0.2.tar.gz (596 kB)
     |████████████████████████████████| 596 kB 6.8 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in d:\programme\blender foundation\blender 2.93.3\2.93\python\lib\site-packages (from laspy) (1.19.5)
Building wheels for collected packages: laspy
  Building wheel for laspy (PEP 517) ... done
  Created wheel for laspy: filename=laspy-2.0.2-py3-none-any.whl size=49993 sha256=19413d9601fba9310236487b57f50a1e54d557162d451e74c628bcc986c6c325
  Stored in directory: c:\users\myname\appdata\local\pip\cache\wheels\48\92\48\491a3a71996fcbed093ee6e203e5a5c810017c4571fc8fcb40
Successfully built laspy
Installing collected packages: laspy
Successfully installed laspy-2.0.2
PS D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\Scripts> ."D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\Scripts\pip.exe" install pyntcloud
Requirement already satisfied: pyntcloud in c:\users\myname\appdata\roaming\python\python39\site-packages (0.1.5)
Requirement already satisfied: pandas in c:\users\myname\appdata\roaming\python\python39\site-packages (from pyntcloud) (1.3.2)
Requirement already satisfied: numpy in d:\programme\blender foundation\blender 2.93.3\2.93\python\lib\site-packages (from pyntcloud) (1.19.5)
Requirement already satisfied: scipy in c:\users\myname\appdata\roaming\python\python39\site-packages (from pyntcloud) (1.7.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\myname\appdata\roaming\python\python39\site-packages (from pandas->pyntcloud) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\myname\appdata\roaming\python\python39\site-packages (from pandas->pyntcloud) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\myname\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.7.3->pandas->pyntcloud) (1.16.0)
```

Package import test:
```
PS D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\Scripts> ."D:\Programme\Blender Foundation\Blender 2.93.3\2.93\python\bin\python.exe"
Python 3.9.2 (default, Mar  1 2021, 08:18:55) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyntcloud
>>> print(pyntcloud)
<module 'pyntcloud' from 'C:\\Users\\myname\\AppData\\Roaming\\Python\\Python39\\site-packages\\pyntcloud\\__init__.py'>
```

**Comment by SBCV** [comment]
Hmm really strange, thanks for those outputs. I'll have a deeper look tomorrow.

**Comment by jjrise** [comment]
> Hmm really strange, thanks for those outputs. I'll have a deeper look tomorrow.

anyone have any luck here? I'm having the same issues on Ubuntu 21.04 with Blender 2.93.4.

**Comment by SBCV** [comment]
Sorry for the late response - I was on vacation and had no access to my desktop pc.
Anyways: I can confirm that this is a **snap specific issue**.

Everything works fine with a local installation of Blender 2.93.4 (on my Ubuntu 18.04 system). That means: download Blender from [here](https://www.blender.org/download/), extract the `blender-2.93.4-linux-x64.tar.xz` archive and run the Blender executable (`blender-2.93.4-linux-x64/blender`)

When I install Blender with `sudo snap install blender --classic`, run Blender with `snap run blender`, open the `Python Console` in Blender and execute
```
>>> import sys
>>> print(sys.executable)
```
I obtain `/snap/blender/624/2.93/python/bin/python3.9`. When running the dependency installation of the addon, I see also something like  
```
INFO:root:INFO: Installing pip!
Defaulting to user installation because normal site-packages is not writeable
...
```
The packages are then installed into `/home/<my_user_name>/.local/lib/python3.9/site-packages` and this is the reason why their are not detected by Blender (which uses `/snap/blender/624/2.93/python/bin/python3.9`). This can be seen by directly importing the dependencies using the `Python Console` of Blender.
```
>>> import pyntcloud
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
ModuleNotFoundError: No module named 'pyntcloud'
```

I'm not a snap expert, but I guess the only workaround is to use a local installation (as described above)

**Comment by tjukanovt** [comment]
I think I am having similar issues. I am using Windows + Blender 3.0 (tried also with 2.93). The steps I am taking are as follows: 

- Start Blender as administrator
- Install the plugin from zip
- Install additional dependencies. Output:
```
Modules Installed (photogrammetry_importer) from 'C:\\Users\\Topi Tjukanov\\Downloads\\photogrammetry_importer.zip' into 'C:\\Users\\Topi Tjukanov\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons'
INFO:root:INFO: Registered Photogrammetry Import Export Addon with 52 modules
INFO:root:INFO: Pip already installed. Using existing pip installation (21.2.3)
INFO:root:INFO: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'pillow']
Collecting pillow
  Downloading Pillow-8.4.0-cp39-cp39-win_amd64.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB 930 kB/s
Installing collected packages: pillow
Successfully installed pillow-8.4.0
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\bin\python.EXE -m pip install --upgrade pip' command.
INFO:root:INFO: Pip already installed. Using existing pip installation (21.2.3)
INFO:root:INFO: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'lazrs']
Collecting lazrs
  Downloading lazrs-0.4.0-cp39-none-win_amd64.whl (370 kB)
     |████████████████████████████████| 370 kB 731 kB/s
Installing collected packages: lazrs
Successfully installed lazrs-0.4.0
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\bin\python.EXE -m pip install --upgrade pip' command.
INFO:root:INFO: Pip already installed. Using existing pip installation (21.2.3)
INFO:root:INFO: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'pylas']
Collecting pylas
  Downloading pylas-0.4.3.tar.gz (31 kB)
Requirement already satisfied: numpy in c:\program files\blender foundation\blender 3.0\3.0\python\lib\site-packages (from pylas) (1.21.2)
Using legacy 'setup.py install' for pylas, since package 'wheel' is not installed.
Installing collected packages: pylas
    Running setup.py install for pylas ... done
Successfully installed pylas-0.4.3
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\bin\python.EXE -m pip install --upgrade pip' command.
INFO:root:INFO: Pip already installed. Using existing pip installation (21.2.3)
INFO:root:INFO: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'pyntcloud']
Collecting pyntcloud
  Downloading pyntcloud-0.1.5-py3-none-any.whl (346 kB)
     |████████████████████████████████| 346 kB 656 kB/s
Requirement already satisfied: numpy in c:\program files\blender foundation\blender 3.0\3.0\python\lib\site-packages (from pyntcloud) (1.21.2)
Requirement already satisfied: scipy in c:\users\topi tjukanov\appdata\roaming\python\python39\site-packages (from pyntcloud) (1.7.3)
Requirement already satisfied: pandas in c:\users\topi tjukanov\appdata\roaming\python\python39\site-packages (from pyntcloud) (1.3.4)
Requirement already satisfied: pytz>=2017.3 in c:\users\topi tjukanov\appdata\roaming\python\python39\site-packages (from pandas->pyntcloud) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\topi tjukanov\appdata\roaming\python\python39\site-packages (from pandas->pyntcloud) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\topi tjukanov\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.7.3->pandas->pyntcloud) (1.16.0)
Installing collected packages: pyntcloud
Successfully installed pyntcloud-0.1.5
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\bin\python.EXE -m pip install --upgrade pip' command.
Info: Pip already installed. Using existing pip installation (21.2.3)
Info: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'pillow']
Info: Pip already installed. Using existing pip installation (21.2.3)
Info: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'lazrs']
Info: Pip already installed. Using existing pip installation (21.2.3)
Info: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'pylas']
Info: Pip already installed. Using existing pip installation (21.2.3)
Info: Installing dependency with ['C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--no-cache-dir', 'pyntcloud']
```
From the GUI everything seems to be in order
![image](https://user-images.githubusercontent.com/13899537/145537220-adef47c8-6ab7-40f0-b3a1-5738cc0e494a.png)

But when I try to import a laz file, suddenly I get an error with Pandas import 🤔

Console output:
```
INFO:root:INFO: path: C:\gis\data\temp_data\blender\L4142G1\L4142G1_3.laz
INFO:root:INFO: Parse Point Data File: ...
Python: Traceback (most recent call last):
  File "C:\Users\Topi Tjukanov\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\photogrammetry_importer\operators\point_data_import_op.py", line 49, in execute
    points = PointDataFileHandler.parse_point_data_file(path, self)
  File "C:\Users\Topi Tjukanov\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\photogrammetry_importer\file_handlers\point_data_file_handler.py", line 204, in parse_point_data_file
    from pyntcloud import PyntCloud
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\pyntcloud\__init__.py", line 1, in <module>
    from .core_class import PyntCloud
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\pyntcloud\core_class.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

location: <unknown location>:-1
```

**Comment by SBCV** [comment]
Can you checkout the latest [commit](d964ef04cefde73320749cc346113e16be5bd73b) or the latest [release](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/releases/tag/v2021.12.28)? It should support now Blender 3.0 and snap based installations.

**Comment by SBCV** [comment]
If it does not work feel free to re-open this issue
