### ISSUE TITLE
LAZ import error: pyo3_runtime.PanicException: index out of range

### ISSUE THREAD

**Issue by tjukanovt** [SBCV/Blender-Addon-Photogrammetry-Importer#43]
I am trying to import a laz file, but I get the following error:

```
location: <unknown location>:-1
INFO:root:INFO: path: C:\gis\data\temp_data\blender\L4142G1\L4142G1_2.laz
INFO:root:INFO: Parse Point Data File: ...
thread '<unnamed>' panicked at 'index 108347 out of range for slice of length 108339', src\libcore\slice\mod.rs:2725:5
Python: Traceback (most recent call last):
  File "C:\Users\Topi Tjukanov\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\photogrammetry_importer\operators\point_data_import_op.py", line 49, in execute
    points = PointDataFileHandler.parse_point_data_file(path, self)
  File "C:\Users\Topi Tjukanov\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\photogrammetry_importer\file_handlers\point_data_file_handler.py", line 238, in parse_point_data_file
    point_cloud = PyntCloud.from_file(ifp)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\pyntcloud\core_class.py", line 130, in from_file
    return cls(**FROM_FILE[ext](filename, **kwargs))
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\pyntcloud\io\las.py", line 90, in read_las
    data = read_las_with_pylas(filename)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\pyntcloud\io\las.py", line 64, in read_las_with_pylas
    las = las_file.read()
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\pylas\lasreader.py", line 64, in read
    points = self._read_points(vlrs)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\pylas\lasreader.py", line 114, in _read_points
    points = self._read_compressed_points_data(laszip_vlr, point_format)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\pylas\lasreader.py", line 136, in _read_compressed_points_data
    decompressed_points = lazrs_decompress_buffer(
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\pylas\compression.py", line 64, in lazrs_decompress_buffer
    lazrs.decompress_points(point_compressed, vlr_data, point_decompressed, parallel)
pyo3_runtime.PanicException: index 108347 out of range for slice of length 108339

location: <unknown location>:-1

```

You can download the file I used [here](https://drive.google.com/file/d/1OoJXVpvhSrT3DbqVGjm-WlP1NAGOnHMi/view?usp=sharing)

**Comment by tjukanovt** [comment]
Apparently when I converted the data to .las using pdal, it seemed to load without any problems.

**Comment by SBCV** [comment]
Thank you for reporting this. Maybe I'll find some time on Sunday to have a look.

Examining the traceback, 

```
location: <unknown location>:-1
INFO:root:INFO: path: C:\gis\data\temp_data\blender\L4142G1\L4142G1_2.laz
INFO:root:INFO: Parse Point Data File: ...
thread '<unnamed>' panicked at 'index 108347 out of range for slice of length 108339', src\libcore\slice\mod.rs:2725:5
Python: Traceback (most recent call last):
  File "C:\Users\Topi Tjukanov\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\photogrammetry_importer\operators\point_data_import_op.py", line 49, in execute
    points = PointDataFileHandler.parse_point_data_file(path, self)
  File "C:\Users\Topi Tjukanov\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\photogrammetry_importer\file_handlers\point_data_file_handler.py", line 238, in parse_point_data_file
    point_cloud = PyntCloud.from_file(ifp)
```

it looks like as the error is actually caused in this line
https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/f79c09ea9eda34574d20ed05ceda9226ce7f778c/photogrammetry_importer/file_handlers/point_data_file_handler.py#L238

Since this function call gets only the path to the input file, this looks like a bug in the `Pyntcloud` library. Have you tried to call `PyntCloud.from_file(ifp)` from a standard Python installation (with the same Pyntcloud version)?

**Comment by Joonalai** [comment]
On Arch Linux the following python (3.9.7) code did provide a wanted result:

```python
# laszip (3.4.3) executable built with LASToos (211112)
from pyntcloud import PyntCloud  # pyntcloud==0.1.5 and pylas==0.4.3

laz_file = "L4142G1_2.laz"
point_cloud = PyntCloud.from_file(laz_file)
print(point_cloud)

"""
PyntCloud
9492321 points with 7 scalar fields
0 faces in mesh
0 kdtrees
0 voxelgrids
Centroid: -125521.828125, -296524.0625, 61.815269470214844
Other attributes:
	 las_header: <class 'pylas.headers.rawheader.RawHeader1_2'>
"""
```

I also tested with pyntcloud 0.1.3 and 0.1.4.

**Comment by SBCV** [comment]
So it runs outside of Blender, but not within? Did you use the same python interpreter?

**Comment by SBCV** [comment]
I just tried to reproduce the results you have posted above.
When running the following commands in `Blender's python console`,
```
from pyntcloud import PyntCloud
print(PyntCloud.from_file("/home/sebastian/Desktop/L4142G1_2.laz"))
```
I obtain (on Ubuntu 18.04) a similar error message:
```
INFO:root:INFO: path: /home/sebastian/Desktop/L4142G1_2.laz
INFO:root:INFO: Parse Point Data File: ...
thread '<unnamed>' panicked at 'assertion failed: mid <= self.len()', /rustc/514b3877956dc594823106b66c164f8cdbc8b3da/library/core/src/slice/mod.rs:1537:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Python: Traceback (most recent call last):
  File "/home/sebastian/.config/blender/3.0/scripts/addons/photogrammetry_importer/operators/point_data_import_op.py", line 49, in execute
    points = PointDataFileHandler.parse_point_data_file(path, self)
  File "/home/sebastian/.config/blender/3.0/scripts/addons/photogrammetry_importer/file_handlers/point_data_file_handler.py", line 238, in parse_point_data_file
    point_cloud = PyntCloud.from_file(ifp)
  File "/mnt/Data-512GB/libraries/blender/blender-3.0.0-linux-x64/3.0/python/lib/python3.9/site-packages/pyntcloud/core_class.py", line 130, in from_file
    return cls(**FROM_FILE[ext](filename, **kwargs))
  File "/mnt/Data-512GB/libraries/blender/blender-3.0.0-linux-x64/3.0/python/lib/python3.9/site-packages/pyntcloud/io/las.py", line 90, in read_las
    data = read_las_with_pylas(filename)
  File "/mnt/Data-512GB/libraries/blender/blender-3.0.0-linux-x64/3.0/python/lib/python3.9/site-packages/pyntcloud/io/las.py", line 64, in read_las_with_pylas
    las = las_file.read()
  File "/mnt/Data-512GB/libraries/blender/blender-3.0.0-linux-x64/3.0/python/lib/python3.9/site-packages/pylas/lasreader.py", line 64, in read
    points = self._read_points(vlrs)
  File "/mnt/Data-512GB/libraries/blender/blender-3.0.0-linux-x64/3.0/python/lib/python3.9/site-packages/pylas/lasreader.py", line 114, in _read_points
    points = self._read_compressed_points_data(laszip_vlr, point_format)
  File "/mnt/Data-512GB/libraries/blender/blender-3.0.0-linux-x64/3.0/python/lib/python3.9/site-packages/pylas/lasreader.py", line 136, in _read_compressed_points_data
    decompressed_points = lazrs_decompress_buffer(
  File "/mnt/Data-512GB/libraries/blender/blender-3.0.0-linux-x64/3.0/python/lib/python3.9/site-packages/pylas/compression.py", line 64, in lazrs_decompress_buffer
    lazrs.decompress_points(point_compressed, vlr_data, point_decompressed, parallel)
pyo3_runtime.PanicException: assertion failed: mid <= self.len()
```

If I type (in `Blender's python console`)
```
import sys
sys.executable
```
it shows the path to the python executable. For me it is something like
```
/mnt/Data-512GB/libraries/blender/blender-3.0.0-linux-x64/3.0/python/bin/python3.9
```
If I run this python version in the standard Ubuntu terminal and execute the same commands,
```
my_user@my_pc:~$ /mnt/Data-512GB/libraries/blender/blender-3.0.0-linux-x64/3.0/python/bin/python3.9 
Python 3.9.7 (default, Oct 11 2021, 10:06:01) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyntcloud import PyntCloud
>>> print(PyntCloud.from_file("/home/sebastian/Desktop/L4142G1_2.laz"))
```
I get the same error message, i.e. 
```
...
line 64, in lazrs_decompress_buffer
    lazrs.decompress_points(point_compressed, vlr_data, point_decompressed, parallel)
pyo3_runtime.PanicException: assertion failed: mid <= self.len()
```
Because of the second last line
```
line 64, in lazrs_decompress_buffer
    lazrs.decompress_points(point_compressed, vlr_data, point_decompressed, parallel)
```
this looks like a bug in a specific `pylas` / `lazrs` version.

Is maybe your `lazrs` version different?

**Comment by Joonalai** [comment]
Actually my Blender crashed when trying to load this but I actually managed to get the lines working in Blender's Python Console. So maybe this is not a bug related to this on my machine.

**Comment by SBCV** [comment]
Side note: I observed that from time to time, some opengl calls cause Blender to crash. So, if you observe something like this, it is usually worth to give it a second try.
