### ISSUE TITLE
Error trying to import .las and .laz files

### ISSUE THREAD

**Issue by flipityflop** [SBCV/Blender-Addon-Photogrammetry-Importer#50]
Hi,
These are the errors I get whenever I try to import a .las or .laz file. I've been trying to get this to work for hours, including manually updating and reinstalling various python packages. I'm basically a beginner when it comes to this stuff, please help. Appreciate the addon, used it a bunch for meshroom data.

```
INFO:root:INFO: path: C:\Users\[name]\Desktop\NUKE\projects\reel\CG_Integration\city_fire_cars\ele\TN_HamiltonCounty_2011_000040.laz
INFO:root:INFO: Parse Point Data File: ...
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pylas\headers\rawheader.py", line 320, in header_class_for_version
    return cls._version_to_header[str(version)]
KeyError: '1.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[name]\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\photogrammetry_importer\operators\point_data_import_op.py", line 49, in execute
    points = PointDataFileHandler.parse_point_data_file(path, self)
  File "C:\Users\[name]\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\photogrammetry_importer\file_handlers\point_data_file_handler.py", line 238, in parse_point_data_file
    point_cloud = PyntCloud.from_file(ifp)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pyntcloud\core_class.py", line 130, in from_file
    return cls(**FROM_FILE[ext](filename, **kwargs))
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pyntcloud\io\las.py", line 90, in read_las
    data = read_las_with_pylas(filename)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pyntcloud\io\las.py", line 63, in read_las_with_pylas
    with pylas.open(filename) as las_file:
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pylas\lib.py", line 66, in open_las
    return LasReader(stream, closefd=closefd)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pylas\lasreader.py", line 39, in __init__
    self.header = self.read_header()
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pylas\lasreader.py", line 45, in read_header
    return headers.HeaderFactory().read_from_stream(self.stream)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pylas\headers\rawheader.py", line 346, in read_from_stream
    header_class = cls.header_class_for_version(version)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pylas\headers\rawheader.py", line 322, in header_class_for_version
    raise errors.FileVersionNotSupported(version)
pylas.errors.FileVersionNotSupported: 1.0

location: <unknown location>:-1
INFO:root:INFO: path: C:\Users\[name]\Desktop\NUKE\projects\reel\CG_Integration\city_fire_cars\ele\2164253NE.las
INFO:root:INFO: Parse Point Data File: ...
WARNING:pylas.lasreader:There are 137 bytes between end of vlrs and start of points
Python: Traceback (most recent call last):
  File "C:\Users\[name]\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\photogrammetry_importer\operators\point_data_import_op.py", line 49, in execute
    points = PointDataFileHandler.parse_point_data_file(path, self)
  File "C:\Users\[name]\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\photogrammetry_importer\file_handlers\point_data_file_handler.py", line 238, in parse_point_data_file
    point_cloud = PyntCloud.from_file(ifp)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pyntcloud\core_class.py", line 130, in from_file
    return cls(**FROM_FILE[ext](filename, **kwargs))
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pyntcloud\io\las.py", line 90, in read_las
    data = read_las_with_pylas(filename)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pyntcloud\io\las.py", line 64, in read_las_with_pylas
    las = las_file.read()
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pylas\lasreader.py", line 92, in read
    evlrs = self.read_evlrs()
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pylas\lasreader.py", line 209, in read_evlrs
    return evlrs.EVLRList.read_from(self.stream, self.header.number_of_evlr)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pylas\evlrs.py", line 89, in read_from
    raw = RawEVLR.read_from(data_stream)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\site-packages\pylas\evlrs.py", line 42, in read_from
    raw_evlr.record_data = data_stream.read(
MemoryError
```

**Comment by SBCV** [comment]
Can you share an example `las` / `laz` file?

**Comment by flipityflop** [comment]
Sure.
[https://drive.google.com/file/d/1x71wYzF79JU7-b6aENL2eTnA1-ZZ2IYm/view?usp=sharing](https://drive.google.com/file/d/1x71wYzF79JU7-b6aENL2eTnA1-ZZ2IYm/view?usp=sharing)

**Comment by SBCV** [comment]
Somehow I receive a different error message:

```
Python: Traceback (most recent call last):
  File "/home/sebastian/.config/blender/3.1/scripts/addons/photogrammetry_importer/operators/point_data_import_op.py", line 49, in execute
    points = PointDataFileHandler.parse_point_data_file(path, self)
  File "/home/sebastian/.config/blender/3.1/scripts/addons/photogrammetry_importer/file_handlers/point_data_file_handler.py", line 238, in parse_point_data_file
    point_cloud = PyntCloud.from_file(ifp)
  File "/mnt/Data-512GB/libraries/blender/blender-3.1.2-linux-x64/3.1/python/lib/python3.10/site-packages/pyntcloud/core_class.py", line 130, in from_file
    return cls(**FROM_FILE[ext](filename, **kwargs))
  File "/mnt/Data-512GB/libraries/blender/blender-3.1.2-linux-x64/3.1/python/lib/python3.10/site-packages/pyntcloud/io/las.py", line 90, in read_las
    data = read_las_with_pylas(filename)
  File "/mnt/Data-512GB/libraries/blender/blender-3.1.2-linux-x64/3.1/python/lib/python3.10/site-packages/pyntcloud/io/las.py", line 64, in read_las_with_pylas
    las = las_file.read()
  File "/mnt/Data-512GB/libraries/blender/blender-3.1.2-linux-x64/3.1/python/lib/python3.10/site-packages/pylas/lasreader.py", line 64, in read
    points = self._read_points(vlrs)
  File "/mnt/Data-512GB/libraries/blender/blender-3.1.2-linux-x64/3.1/python/lib/python3.10/site-packages/pylas/lasreader.py", line 114, in _read_points
    points = self._read_compressed_points_data(laszip_vlr, point_format)
  File "/mnt/Data-512GB/libraries/blender/blender-3.1.2-linux-x64/3.1/python/lib/python3.10/site-packages/pylas/lasreader.py", line 136, in _read_compressed_points_data
    decompressed_points = lazrs_decompress_buffer(
  File "/mnt/Data-512GB/libraries/blender/blender-3.1.2-linux-x64/3.1/python/lib/python3.10/site-packages/pylas/compression.py", line 64, in lazrs_decompress_buffer
    lazrs.decompress_points(point_compressed, vlr_data, point_decompressed, parallel)
pyo3_runtime.PanicException: assertion failed: mid <= self.len()

location: <unknown location>:-1
```
 
This error message is similar to #43

**Comment by SBCV** [comment]
> I believe that's the one I've been trying.

Can you double check, that this is the correct file?

**Comment by SBCV** [comment]
Following the steps in #43, I can reproduce this error (`pyo3_runtime.PanicException: assertion failed: mid <= self.len()`) outside of Blender

**Comment by SBCV** [comment]
Found out out that this is a `pylas` specific issue. However, it works with `laspy 2.X`.
Laspy 2.X is a merge of pylas and Laspy 1.X, and is therefore available for python with pip.
Fore more information, see [this link](https://laspy.readthedocs.io/en/latest/)

To fix this issue, I'll create a PR for Pyntcloud. However, it might take some time until the updated Pyntcloud version is available with pip. Of course you could also manually adjust the Pyntcloud library and install it for Blender.

**Comment by flipityflop** [comment]
I don't know how to manually adjust a library, I basically just crash coursed Python in the past 2 days trying to figure this out. I do have `laspy` installed and its giving me an error that I need to have `pylas` installed.
Also, I just realized that I should clarify that I'm running Windows.

**Comment by flipityflop** [comment]
So I have no idea why, but after reinstalling `pylas`, it magically starting working, but only the `.LAS` files, not the `.LAZ`. 
I guess haleluyah?, and the key to software is to keep trying the same things over and over until it works. 
Let me know if you need any sort of logs or debug info.

**Comment by SBCV** [comment]
> OpenGL Point Cloud imports as a single empty, whereas import mesh works. Something is very wrong with the way Blender is working with Point Clouds and I can't figure it out.

The way Blender treats point clouds is indeed a bit frustrating - actually the limitations of Blender's native point cloud importer are so severe, that I wrote a custom visualizing option using OpenGL.

This visualizing component uses an `empty` to control the pose of the points. Thus, the import of a single empty should be correct.

The why you can not see your points is that your points contain very large offsets. Therefore, they are far away from the origin and potentially outside of Blender's clipping distance. In the latest commit, I've added an option to center the imported point cloud to address this issue.

Here is an example screenshot:

![image](https://user-images.githubusercontent.com/19491335/170527903-b3778970-77c4-4a0e-b8e3-ccb8de566092.png)

**Comment by flipityflop** [comment]
> In the latest commit, I've added an option to center the imported point cloud to address this issue.

Just downloaded, works great. Now I have to figure out a way to turn this into a functioning mesh. Appreciate the help!

**Comment by SBCV** [comment]
> Now I have to figure out a way to turn this into a functioning mesh.

I do not know, if Blender is the best tool for that (I would checkout the functionality of [Meshlab](https://www.meshlab.net/) or [CloudCompare](https://www.danielgm.net/cc/) for a task like this).

In case Blender has some appropriate functionality, I think your best option is to import the point cloud as `mesh object`. This way you have a standard Blender object, which should be compatible to Blender's algorithms.

![image](https://user-images.githubusercontent.com/19491335/170555429-766e73ab-a25c-406d-8370-f699902c92a4.png)

> PS. I don't think the batch file to create a .zip actually works, or at least I cant figure out where it gets put. I had to create one myself, manually. Or maybe I just don't know how to properly execute batch files.

Actually you don't have to provide any input, just call it without parameters. Can you check again?

**Comment by flipityflop** [comment]
It does seem to be working after installing git, but the `.zip` it creates is empty.

**Comment by SBCV** [comment]
Okay, I will double check on my windows system

**Comment by SBCV** [comment]
Pylas 2.x is now supported: https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/commit/91fe0bb007e3011bf125abdd1fcb6de9037d3b3e

**Comment by SBCV** [comment]
> It does seem to be working after installing git, but the .zip it creates is empty.

Ah, I've just realized why it is not working for you. Currently the script requires that the addon folder was acquired with git (i.e. `git clone https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer.git`).

If you just downloaded the addon from the github-gui as archive, it does not contain the repository information and the script does not work. Thank you for reporting this - will fix it soon.

**Comment by flipityflop** [comment]
> If you want to correctly import color values, see [daavoo/pyntcloud#331](https://github.com/daavoo/pyntcloud/issues/331) and [laspy/laspy#221](https://github.com/laspy/laspy/issues/221)

I think this was the reason that re export into `Alembic` wasn't working properly in Nuke. I have to test that though.

**Comment by flipityflop** [comment]
> Pylas 2.x is now supported: [91fe0bb](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/commit/91fe0bb007e3011bf125abdd1fcb6de9037d3b3e)

How do I integrate this into what I already have.

**Comment by SBCV** [comment]
Since I do not know, how your current configuration looks at the moment, I guess the best option is to:

- Use the addon to uninstall all dependencies
- Uninstall the addon
- **close** Blender (!!!) to clear all references to previously installed python modules
- install the new version of the addon
- install the dependencies

Of course you can also upgrade the dependencies using pip. However, in this case there are also changes to the addon, so I don't know if that is the best option.

**Comment by SBCV** [comment]
FYI: https://blender-addon-photogrammetry-importer.readthedocs.io/en/latest/installation.html#option-2-installation-using-the-command-line

**Comment by SBCV** [comment]
Can you check, if `create_blender_addon_zip.bat` of the latest commit (https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/commit/eaf4f55046d74c6977360821ce22f7e113ab8329) works for you?

**Comment by flipityflop** [comment]
It does work, but only if I download the zip manually, not if I install from `CLI`.
The distinction of which script to run might be unclear to beginners like me.

**Comment by flipityflop** [comment]
If I download `Blender-Addon-Photogrammetry-Importer` from the command line with the following code: `gh repo clone SBCV/Blender-Addon-Photogrammetry-Importer`, than the `.bat` file does nothing, whereas if I download the `ZIP` directly from the dropdown on GitHub, then it works as intended.

**Comment by flipityflop** [comment]
Ok, I take it all back, I think it wasn't working because I had downloaded it into `C:\WINDOWS\system32>` without thinking, and so I think it was a permissions issue. I've redownloaded using the same method into the `Desktop` folder and the `.bat` ran as intended.

**Comment by SBCV** [comment]
Can we close this issue, or is there something still open?

**Comment by flipityflop** [comment]
I have to say, the amount of time and effort you out into ironing out issues on a free addon is really awesome. Thanks for taking the time. Let me know if you ever need any testing or logs or something like that.
