### ISSUE TITLE
Python KeyError

### ISSUE THREAD

**Issue by scottsegler** [SBCV/Blender-Addon-Photogrammetry-Importer#56]
I am so sorry to trouble anyone, especially if I have done something wrong on my end.

I switched to using Meshroom 2023.1.0 from Meshroom 2021.1.0.  I use the ConvertSfMFormat module in Meshroom to generate the SfM File Format to bring into Blender.  I am getting error messages when trying to import SFM to Blender.  I received the error when using Blender 3.2 with Photogrammetry Import Export Addon V 3.

I also received the error when I updated to Blender 3.5.1 and Photogrammetry Import Export Addon V 3.2.1.  

The error reads as follows:

path: E:\2023 0427 Nikon Z9 Test Hyperlapse Chrysler Building\Meshroom\MeshroomCache\ConvertSfMFormat\d8a89f83c33daf9affe1274217752a01d4a7f35b\sfm.sfm
parse_meshroom_file: ...
meshroom_ifp: E:\2023 0427 Nikon Z9 Test Hyperlapse Chrysler Building\Meshroom\MeshroomCache\ConvertSfMFormat\d8a89f83c33daf9affe1274217752a01d4a7f35b\sfm.sfm
parse_meshroom_sfm_file: ...
sfm_ifp: E:\2023 0427 Nikon Z9 Test Hyperlapse Chrysler Building\Meshroom\MeshroomCache\ConvertSfMFormat\d8a89f83c33daf9affe1274217752a01d4a7f35b\sfm.sfm
Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\photogrammetry_importer\operators\meshroom_import_op.py", line 107, in execute
    ) = MeshroomFileHandler.parse_meshroom_file(
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\photogrammetry_importer\file_handlers\meshroom_file_handler.py", line 494, in parse_meshroom_file
    cams, points = cls.parse_meshroom_sfm_file(
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\photogrammetry_importer\file_handlers\meshroom_file_handler.py", line 187, in parse_meshroom_sfm_file
    ) = cls._parse_cameras_from_json_data(
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\photogrammetry_importer\file_handlers\meshroom_file_handler.py", line 95, in _parse_cameras_from_json_data
    focal_length = float(intrinsic_params["pxFocalLength"])
KeyError: 'pxFocalLength'

**Comment by scottsegler** [comment]
I had updated it by downloading the photogrammetry_importer.zip from the
release page, choosing the latest Release 21/07/2022 (Compatible with
Blender 3.1.2 - 3.2.1).

To clone it, I downloaded the zip and re-zipped the underlying
photogrammetry_importer folder.  Then I reinstalled in Blender 3.5.

Perfection!  I'm back in business.  It is working with Meshroom 2023 data
in Blender 3.5 with add-on Version 3.2.1 as cloned.  Thank you so much for
your help.

**Comment by scottsegler** [comment]
On a closer look, it appears that the focal lengths of the Animated Cameras
as imported using the SfM file in Blender are corrupted.  The focal length
in my particular data is imported as a fraction of a millimeter, whereas it
should be roughly 20mm.

**Comment by SBCV** [comment]
Maybe they changed the semantic of the focal length value.
At the moment I have not that much spare time - I'll check, if I can have a look next weekend.

**Comment by scottsegler** [comment]
Thank you so much for your work on this project. I am such a huge fan of
yours on this importer.  The incorrect focal length can easily be
overridden in Blender and otherwise does not seem to be a problem.

**Comment by scottsegler** [comment]
All appears to be working perfectly now...the data imported to Blender
includes the correct focal length.  Thanks so much!
