### ISSUE TITLE
I get an import error.

### ISSUE THREAD

**Issue by fnami86** [SBCV/Blender-Addon-Photogrammetry-Importer#62]
Looking at the blender info, it seems that there is an error on line 576 and line 269 of A. Is there a workaround?

Python: Traceback (most recent call last):
  File "C:\Users\YY\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\photogrammetry_importer\operators\meshroom_import_op.py", line 107, in execute
    ) = MeshroomFileHandler.parse_meshroom_file(
  File "C:\Users\YY\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\photogrammetry_importer\file_handlers\meshroom_file_handler.py", line 576, in parse_meshroom_file
    cams, points = cls.parse_meshroom_sfm_file(
  File "C:\Users\YY\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\photogrammetry_importer\file_handlers\meshroom_file_handler.py", line 269, in parse_meshroom_sfm_file
    ) = cls._parse_cameras_from_json_data(
  File "C:\Users\YY\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\photogrammetry_importer\file_handlers\meshroom_file_handler.py", line 136, in _parse_cameras_from_json_data
    raise NotImplementedError
NotImplementedError

**Comment by lfertig** [comment]
can confirm the error, happens despite enabling camera import

**Comment by lfertig** [comment]
a quick followup on this one, the code for AliceVision version 1.2.2. seems to work fine for me, only difference being that the cameras come in rotated 180º around the x axis. I cant quite tell yet if the latter is because of the version or originates from another problem.

**Comment by qpski25** [comment]
how did you downgrade the code?

**Comment by lfertig** [comment]
to see if it worked i just copied the code from [here](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/da404ebf8d4412196c2740f0b569cbf9e542952d/photogrammetry_importer/file_handlers/meshroom_file_handler.py#L145)  to the if statement before in line 140. seemed to work fine but i still have to look into the version if anything actually changed. im not familiar with the actual alice vision code/file format

**Comment by SBCV** [comment]
Fixed in 7dc5d44423a01a8a56a0e141be3c102672c50d14
Can you check if everything works for you when you use the most recent version?
If not let me know.

**Comment by SBCV** [comment]
Feel free to reopen

**Comment by qpski25** [comment]
where/how do i paste the code into the add-on ?

**Comment by lfertig** [comment]
from what sbcv said you just need to update to the latest version. the fix he posted changes the code to accept version 1.2.6. i havent tested it yet, still on vacation :)
