### ISSUE TITLE
Trying to import sfm to blender and this code keeps coming back.

### ISSUE THREAD

**Issue by qpski25** [SBCV/Blender-Addon-Photogrammetry-Importer#63]
Python: Traceback (most recent call last):
  File "C:\Users\QP\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\photogrammetry_importer\operators\meshroom_import_op.py", line 107, in execute
    ) = MeshroomFileHandler.parse_meshroom_file(
  File "C:\Users\QP\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\photogrammetry_importer\file_handlers\meshroom_file_handler.py", line 576, in parse_meshroom_file
    cams, points = cls.parse_meshroom_sfm_file(
  File "C:\Users\QP\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\photogrammetry_importer\file_handlers\meshroom_file_handler.py", line 269, in parse_meshroom_sfm_file
    ) = cls._parse_cameras_from_json_data(
  File "C:\Users\QP\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\photogrammetry_importer\file_handlers\meshroom_file_handler.py", line 136, in _parse_cameras_from_json_data
    raise NotImplementedError
NotImplementedError

**Comment by SBCV** [comment]
Should be fixed in 7dc5d44423a01a8a56a0e141be3c102672c50d14
If not, feel free to reopen
