### ISSUE TITLE
keep getting error loading

### ISSUE THREAD

**Issue by Zevram** [SBCV/Blender-Addon-Photogrammetry-Importer#7]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Guillermo\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\photogrammetry_importer\__init__.py", line 42, in <module>
    modules = developer_utils.setup_addon_modules(__path__, __name__, "bpy" in locals())
  File "C:\Users\Guillermo\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\photogrammetry_importer\developer_utils.py", line 39, in setup_addon_modules
    modules = import_submodules(names)
  File "C:\Users\Guillermo\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\photogrammetry_importer\developer_utils.py", line 30, in import_submodules
    modules.append(importlib.import_module("." + name, package_name))
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Guillermo\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\photogrammetry_importer\photogrammetry_import_op.py", line 9, in <module>
    from photogrammetry_importer.file_handler.meshroom_json_file_handler import MeshroomJSONFileHandler
  File "C:\Users\Guillermo\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\photogrammetry_importer\file_handler\meshroom_json_file_handler.py", line 4, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

your suggetion

**Comment by SBCV** [comment]
Thank you for reporting this. The latest commit should fix this problem. Can you check if everything works for you?
If you want to load the images associated with your reconstruction you need to install PIL / Pillow anyways. See the reconstruction guidelines here: https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/master/doc/markdown/installation.md

**Comment by Electrongap** [comment]
I sorted it by following this https://blender.stackexchange.com/questions/119051/how-do-i-install-pillow-and-or-pip-in-blender-python-in-windows-os
Basically navigate to the python/bin folder using Powershell then follow the guide.

**Comment by SBCV** [comment]
I will probably remove this (legacy) dependency when i get some more spare time. Using pillow makes sense using these scripts outside of Blender. But inside of a Blender addon we can replace pillow with Blenders built-in image handling functionality

**Comment by SBCV** [comment]
I just figured out that accessing pixel values using the blender image API is incredible slow in comparison to pillow. Therefore, pillow will remain as dependency. 
However, Pillow is only necessary to 
- compute color information for OpenMVG (JSON) files
- read image sizes for VisualSFM (NVM) files
