### ISSUE TITLE
Compatibility with blender 4.0 for colmap projects

### ISSUE THREAD

**Issue by marinmarcillat** [SBCV/Blender-Addon-Photogrammetry-Importer#70]
Hello,

When trying to import a Colmap project in Blender 4.0.2, I faced an error during point importation:

> Python: Traceback (most recent call last):
  File "C:\Users\Administrateur\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\photogrammetry_importer\operators\colmap_import_op.py", line 60, in execute
    self.import_photogrammetry_points(points, reconstruction_collection)
  File "C:\Users\Administrateur\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\photogrammetry_importer\importers\point_importer.py", line 117, in import_photogrammetry_points
    draw_points(
  File "C:\Users\Administrateur\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\photogrammetry_importer\opengl\utility.py", line 52, in draw_points
    object_anchor_handle = _draw_coords_with_color(
  File "C:\Users\Administrateur\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\photogrammetry_importer\opengl\utility.py", line 34, in _draw_coords_with_color
    draw_manager.register_points_draw_callback(
  File "C:\Users\Administrateur\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\photogrammetry_importer\opengl\draw_manager.py", line 54, in register_points_draw_callback
    draw_callback_handler = _DrawCallBackHandler()
  File "C:\Users\Administrateur\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\photogrammetry_importer\opengl\draw_manager.py", line 101, in __init__
    self._shader = gpu.shader.from_builtin("3D_FLAT_COLOR")
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '3D_FLAT_COLOR'

I believe this might be related to the new 4.0 version because it works well in Blender 3.6 LTS. If I have time I will try to investigate this issue.
Thank you for this great add-on !

Marin

**Comment by SBCV** [comment]
Has been fixed in #71
