### ISSUE TITLE
error when importing colmap folder into blender through the plugin

### ISSUE THREAD

**Issue by arielcaine** [SBCV/Blender-Addon-Photogrammetry-Importer#8]
#5 
when attempting to imort colmap folder (the model is exported as text from colmap resulting in camera, images, points3D .txt files) i get an error and nothing is loaded in blender.  
however for some reason the example colmap folder that comes with the addon imports fine. 

the error i get is this:
Traceback (most recent call last):
  File "C:\Users\ariel caine\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\photogrammetry_importer\photogrammetry_import_op.py", line 81, in execute
    cameras, points = ColmapFileHandler.parse_colmap_model_folder(path, self)
  File "C:\Users\ariel caine\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\photogrammetry_importer\file_handler\colmap_file_handler.py", line 146, in parse_colmap_model_folder
    id_to_col_cameras, id_to_col_images, op)
  File "C:\Users\ariel caine\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\photogrammetry_importer\file_handler\colmap_file_handler.py", line 87, in convert_cameras
    assert len(camera_models) == 1
AssertionError

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by SBCV** [comment]
Maybe the author of colmap changed the data format? Can you share the reconstruction result with me? Preferably as .txt files?

**Comment by SBCV** [comment]
@arielcaine have you resolved your problem?

**Comment by SteffenDuenner** [comment]
I had a similar problem when I didn't check "Shared for all images" for feature extraction. I suspect that the plugin can't import varying camera intrinsics but only a single one. I tried to import the camera animation BTW.

**Comment by SBCV** [comment]
Thanks for pointing that out - gives me an idea where to look! 
And it makes sense, looking at the assertion above. 
The question is how to resolve this (afaik blender's  camera render setting is restricted to 1 camera). I'll have a look.

**Comment by SBCV** [comment]
Removed this limitation in the latest commit. Feel free to reopen this issue, if you experience any problems.
