### ISSUE TITLE
Can not donwload the depencies from the GUI on blender 4.0.2 or 4.1 or 4.2.

### ISSUE THREAD

**Issue by dororo-ak** [SBCV/Blender-Addon-Photogrammetry-Importer#82]
Hi,
I'm writting this issue because each time I try to doanload depencies I have these errors : 

Python: Traceback (most recent call last):
  File "C:\Users\adama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\photogrammetry_importer\preferences\dependency.py", line 365, in execute
    dependency_manager.install_dependencies(
  File "C:\Users\adama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\photogrammetry_importer\preferences\dependency.py", line 317, in install_dependencies
    dependency.install(op=op)
  File "C:\Users\adama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\photogrammetry_importer\preferences\dependency.py", line 226, in install
    importlib.import_module(self.import_name)
  File "C:\Program Files\Blender Foundation\blender-4.0.2-windows-x64\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Blender Foundation\blender-4.0.2-windows-x64\4.0\python\lib\site-packages\setuptools\__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "C:\Program Files\Blender Foundation\blender-4.0.2-windows-x64\4.0\python\lib\site-packages\_distutils_hack\override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "C:\Program Files\Blender Foundation\blender-4.0.2-windows-x64\4.0\python\lib\site-packages\_distutils_hack\__init__.py", line 77, in do_override
    ensure_local_distutils()
  File "C:\Program Files\Blender Foundation\blender-4.0.2-windows-x64\4.0\python\lib\site-packages\_distutils_hack\__init__.py", line 64, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: C:\Program Files\Blender Foundation\blender-4.0.2-windows-x64\4.0\python\lib\distutils\core.py

When I try to download one by one: e.g pyntcloud
bpy.ops.photogrammetry_importer.install_dependencies(dependency_package_name="pyntcloud")
Pip already installed. Using existing pip installation (23.0.1)
Installing dependency with ['C:\\Program Files\\Blender Foundation\\blender-4.0.2-windows-x64\\4.0\\python\\bin\\python.exe', '-m', 'pip', 'install', '--no-cache-dir', 'pyntcloud']
===========================================
INSTALLATION of DEPENDENCY pyntcloud FAILED!
Reason: No module named 'pyntcloud'
===========================================

**Comment by soans1994** [comment]
same

**Comment by SBCV** [comment]
As stated [here](https://blender-photogrammetry-importer.readthedocs.io/en/latest/installation.html#option-1-installation-using-the-gui-recommended) : depending on the location you need administrator privileges. Try to install Blender to a different location or download a portable version.

Re-open if the problem persists
